export const CUSTOMER_REGISTER = 'CUSTOMER_REGISTER';
export const FETCH_USER_LOGIN_SUCCES = 'FETCH_USER_LOGIN_SUCCES';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
